import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">OTT</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/legacyofthesandalwood">LegacyoftheSandalwood</Link>
        </li>
        <li>
          <Link to="/birthday">Birthday</Link>
        </li>
        <li>
          <Link to="/publicratingtwo">PublicRatingTwo</Link>
        </li>
        <li>
          <Link to="/traininginstitutes">TrainingInstitutes</Link>
        </li>
        <li>
          <Link to="/myprofile">MyProfile</Link>
        </li>
        <li>
          <Link to="/searchpanel">Searchpanel</Link>
        </li>
        <li>
          <Link to="/mainscreen">MainScreen</Link>
        </li>
        <li>
          <Link to="/signout">Signout</Link>
        </li>
        <li>
          <Link to="/contactus">Contactus</Link>
        </li>
        <li>
          <Link to="/loginregisterone">LoginRegisterOne</Link>
        </li>
        <li>
          <Link to="/legendsoftheindustryone">LegendsoftheindustryOne</Link>
        </li>
        <li>
          <Link to="/livinglegends">LivingLegends</Link>
        </li>
        <li>
          <Link to="/legendsofindustry2">Legendsofindustry2</Link>
        </li>
        <li>
          <Link to="/loginregisterfilmperson">LoginRegisterFilmPerson</Link>
        </li>
        <li>
          <Link to="/loginregisterindustryselection">
            LoginRegisterIndustrySelection
          </Link>
        </li>
        <li>
          <Link to="/loginregistercinemaprofessionalone">
            LoginRegisterCinemaProfessionalOne
          </Link>
        </li>
        <li>
          <Link to="/loginregisteradagencypromoter">
            LoginRegisterAdAgencyPromoter
          </Link>
        </li>
        <li>
          <Link to="/loginregisterproductionhousecompany">
            LoginRegisterProductionHouseCompany
          </Link>
        </li>
        <li>
          <Link to="/registrationformone">RegistrationFormOne</Link>
        </li>
        <li>
          <Link to="/registrationformfour">RegistrationFormFour</Link>
        </li>
        <li>
          <Link to="/promotemaster">PromoteMaster</Link>
        </li>
        <li>
          <Link to="/auditionscallregistration">AuditionsCallRegistration</Link>
        </li>
        <li>
          <Link to="/auditionscallpageone">AuditionscallpageOne</Link>
        </li>
        <li>
          <Link to="/auditionscallpage">Auditionscallpage</Link>
        </li>
        <li>
          <Link to="/registrationformseven">RegistrationFormSeven</Link>
        </li>
        <li>
          <Link to="/plansone">PlansOne</Link>
        </li>
        <li>
          <Link to="/planstwo">PlansTwo</Link>
        </li>
        <li>
          <Link to="/filimfestivalone">FilimFestivalOne</Link>
        </li>
        <li>
          <Link to="/filmfestivalregistration">FilmFestivalRegistration</Link>
        </li>
        <li>
          <Link to="/filimfestival">FilimFestival</Link>
        </li>
        <li>
          <Link to="/awardnews">AwardNews</Link>
        </li>
        <li>
          <Link to="/mainscreenone">MainScreenOne</Link>
        </li>
        <li>
          <Link to="/filmindusry">FilmIndusry</Link>
        </li>
        <li>
          <Link to="/filmupdates">Filmupdates</Link>
        </li>
        <li>
          <Link to="/menu">Menu</Link>
        </li>
        <li>
          <Link to="/menuone">MenuOne</Link>
        </li>
        <li>
          <Link to="/profile">Profile</Link>
        </li>
        <li>
          <Link to="/uploadmycomputerfileupload">
            UploadMyComputerFileUpload
          </Link>
        </li>
        <li>
          <Link to="/uploadtoottpriceplan">UploadtoOTTPricePlan</Link>
        </li>
        <li>
          <Link to="/watchlist">Watchlist</Link>
        </li>
        <li>
          <Link to="/uploaddragfilefileupload">UploadDragFileFileUpload</Link>
        </li>
        <li>
          <Link to="/career">Career</Link>
        </li>
        <li>
          <Link to="/notification">Notification</Link>
        </li>
        <li>
          <Link to="/loginregisterindustryselectionone">
            LoginRegisterIndustrySelectionOne
          </Link>
        </li>
        <li>
          <Link to="/loginregisterfilmlover">LoginRegisterFilmLover</Link>
        </li>
        <li>
          <Link to="/registrationformtwo">RegistrationFormTwo</Link>
        </li>
        <li>
          <Link to="/loginregistercinemaprofessionaltwo">
            LoginRegisterCinemaProfessionalTwo
          </Link>
        </li>
        <li>
          <Link to="/registrationformfive">RegistrationFormFive</Link>
        </li>
        <li>
          <Link to="/uploadpremieryourmovieoncinemadbscom">
            UploadPremieryourmovieonCinemaDBScom
          </Link>
        </li>
        <li>
          <Link to="/copyright">Copyright</Link>
        </li>
        <li>
          <Link to="/termsconditions">TermsConditions</Link>
        </li>
        <li>
          <Link to="/uploadtofilimfestivalone">UploadtoFilimFestivalOne</Link>
        </li>
        <li>
          <Link to="/uploadtofilimfestivaltwo">UploadtoFilimFestivalTwo</Link>
        </li>
        <li>
          <Link to="/registrationformthree">RegistrationFormThree</Link>
        </li>
        <li>
          <Link to="/registrationformsix">RegistrationFormSix</Link>
        </li>
        <li>
          <Link to="/offers">Offers</Link>
        </li>
        <li>
          <Link to="/qa">QA</Link>
        </li>
        <li>
          <Link to="/disclaimer">Disclaimer</Link>
        </li>
        <li>
          <Link to="/eventtickets">EventTickets</Link>
        </li>
        <li>
          <Link to="/eventsregistration">EventsRegistration</Link>
        </li>
        <li>
          <Link to="/demoregistrationformforff1">
            DEMOREGISTRATIONFORMforFF1
          </Link>
        </li>
        <li>
          <Link to="/demoregistrationformforcinemafans">
            DEMOREGISTRATIONFORMforCinemaFANS
          </Link>
        </li>
        <li>
          <Link to="/promotiontermconduction">PromotionTermconduction</Link>
        </li>
        <li>
          <Link to="/privacypolicy">Privacypolicy</Link>
        </li>
        <li>
          <Link to="/demoregistrationformforfftwo">
            DEMOREGISTRATIONFORMforFFTwo
          </Link>
        </li>
        <li>
          <Link to="/payments12cards">Payments12cards</Link>
        </li>
        <li>
          <Link to="/payments">Payments</Link>
        </li>
        <li>
          <Link to="/penman">Penman</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
